POST http://localhost:8080/api/v1/templates/35458f63-0486-4f8b-a2af-5b026148fc2f/process
Accept-Language: de
Content-Type: application/json

{
  "name": "Silvio",
  "dob": "2022-01-03"
}

###

POST http://localhost:8080/api/v1/templates/
Content-Type: application/json
Accept: application/json

{
  "name": "Silvios Template",
  "contentType": "text/plain",
  "content": "Hello [(${document.name})], date of birth: [(${document.dob})]\nLang: [(${#locale.language})]"
}

