name: Release

on:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      M2_USER: ${{ secrets.M2_USER }}
      M2_PWD: ${{ secrets.M2_PWD }}
      GESUS_ARTIFACTORY_USER: ${{ secrets.M2_USER }}
      GESUS_ARTIFACTORY_PASS: ${{ secrets.M2_PWD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Prepare
      id: prepare
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "gh-actions@wangler.io"
        git fetch --tags
        sudo apt update
        sudo apt install -y --no-install-recommends libreoffice-writer

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Publish to GitHub Packages
      uses: gradle/gradle-build-action@v2
      with:
        arguments: artifactoryPublish publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish tag
      uses: ad-m/github-push-action@master
      with:
        tags: true
        branch: ${{ env.BRANCH_NAME }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
